"""add Abstract mixin changes

Revision ID: a1492e5baad8
Revises: ba98d4964f3c
Create Date: 2023-04-04 20:10:40.993642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1492e5baad8'
down_revision = 'ba98d4964f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
